feat(arch::docker): add archive, base, dev, testing & slim

diff --git a/src/pacman-static/Dockerfile b/src/pacman-static/Dockerfile
--- a/src/pacman-static/Dockerfile
+++ b/src/pacman-static/Dockerfile
@@ -1,16 +1,47 @@
 # syntax=docker/dockerfile:1
 FROM ghcr.io/archlinux/archlinux as arch
-FROM ghcr.io/2moe/zsh-static as zsh
-FROM curlimages/curl as pacman-static
 
-ARG OPT=/opt/bin
-COPY --from=zsh ${OPT}/zsh /app/
+FROM ghcr.io/2moe/zsh-static as zsh
+# ENV PATH=/opt/bin:/opt/busybox
+# src: ../../ca-certificates/extracted/tls-ca-bundle.pem
+# link: /etc/ssl/certs/ca-certificates.crt
+ARG CA_FILE=/etc/ca-certificates/extracted/tls-ca-bundle.pem
+ARG TLS_CRT=/etc/ssl/certs/ca-certificates.crt
+COPY --from=arch ${CA_FILE} ${CA_FILE}
+COPY --from=arch ${TLS_CRT} ${TLS_CRT}
+# ARG TERM_INFO=/usr/share/terminfo
+# COPY --from=arch ${TERM_INFO} ${TERM_INFO}
+COPY . /etc/
+
+ARG OS_ARCH
+RUN <<UPDATE_PACMAN_D
+    ln -svf ${CA_FILE} ${TLS_CRT}
+
+    cd /opt/bin
+    ln -svf $PWD/pacman-static /opt/pack
+
+    cd /opt
+
+    chmod 755 -v /etc/pacman.d
+
+    cd /etc/pacman.d/repos
+    for i (disabled/${OS_ARCH}/*conf) {
+        cp -Lvf $i .
+    }
+
+    cd ../options
+    ln -svf bak/siglevel-never.conf ./sig-level.conf
+    mkdir -p /var/lib/pacman/
+    rm /*.core ||:
+UPDATE_PACMAN_D
 # -----------------
+# -----------------
+FROM curlimages/curl as pacman-static
+COPY --from=zsh /opt/bin/zsh /app/
 USER 0:0
 
-# build-args
+ARG OS_ARCH
 ARG REGION
-ARG OS_ARCH=x86_64
 # -----------------
 RUN <<GET_PACMAN
 #!/app/zsh
@@ -35,8 +66,8 @@ RUN <<GET_PACMAN
         )
 
         case $pkg {
-            (pacman-*tar.*) ;;
-            (*) pkg=pacman-static-6.1.0-1-x86_64.pkg.tar.zst ;;
+            (pacman-static-*tar.*) ;;
+            (*) pkg=pacman-static-6.1.0-1-${OS_ARCH}.pkg.tar.zst ;;
         }
         curl -Lo $pkg ${mirror_url}${pkg}
     }
@@ -52,52 +83,169 @@ RUN <<GET_PACMAN
     download
     extract_pkg
 GET_PACMAN
+
+COPY --chmod=755 <<'PRINT_CMD' /app/print-cmd
+#!/opt/bin/zsh -fe
+    args=("%F{green}$1%f")
+    shift
+    for a ($*) {
+        case $a {
+            (--*)  args+="%F{blue}$a%f"  ;;
+            (-*)   args+="%F{cyan}$a%f"  ;;
+            (*)    args+=$a              ;;
+        }
+    }
+    print -Pr >&2 -- "$args"
+PRINT_CMD
+
+COPY --chmod=755 <<'PACMAN_ALT' /app/pacman
+#!/opt/bin/zsh
+    set -feo pipefail
+    local -r src=${0:a}
+    stderr() {
+        print -Pr >&2 -- "$*"
+    }
+
+    bin_pacman=/bin/pacman
+    opt_pacman=/opt$bin_pacman
+    local cmd
+    if [[ -e $bin_pacman ]] {
+        cmd=(unlink $src)
+        print-cmd $cmd
+        $cmd
+
+        cmd=($bin_pacman $*)
+        print-cmd $cmd
+        $cmd
+        local status=$?
+
+        stderr run %F{green}hash %F{cyan}-r%f to reset the command hash table.
+        exit $status
+    }
+
+    if ((# == 0)) {
+        ${opt_pacman}-static
+        exit $?
+    }
+    case $1 {
+        (-S*)
+            cmd=(${opt_pacman}-static $* --overwrite '*')
+            print-cmd $cmd
+            $cmd
+        ;;
+        (*) ${opt_pacman}-static $* ;;
+    }
+PACMAN_ALT
+
+COPY --chmod=755 <<'PACMAN_INSTALL' /app/pacman-install
+#!/opt/bin/zsh
+    set -feo pipefail
+    stderr() {
+        print -Pr >&2 -- "$*"
+    }
+    error() {
+        stderr "%F{red}[ERROR]%f $*"
+    }
+
+    cmd=()
+    if (( $(id -u) != 0 )) {
+        stderr '%F{yellow}[WARN]%f You should run it as %F{magenta}root%f.'
+        if (($+commands[sudo])) {
+            cmd+=sudo
+        }
+        if (($+commands[doas])) {
+            cmd+=doas
+        }
+        if ((! $+cmd[1])) {
+            exit 1
+        }
+    }
+    pacman_installed=false
+    for i (/opt/bin/pacman-static /bin/pacman $commands[pacman]) {
+        if [[ -e $i ]] {
+            cmd+=$i
+            pacman_installed=true
+            break
+        }
+    }
+    if {! $pacman_installed} {
+        error "Please install %F{blue}pacman%f first."
+        exit 127
+    }
+    if ((! #1)) {
+        cmd+="-Syu"
+        print-cmd $cmd
+        $cmd
+        exit $?
+    }
+
+    installation_cmd=(
+        $cmd
+        --overwrite '*'
+        --noconfirm
+        -Sy
+    )
+    failures=()
+    for i ($*) {
+        cmd=($installation_cmd $i)
+        print-cmd $cmd
+        $cmd || failures+=$i
+    }
+
+    if (($+failures[1])) {
+        (
+            IFS=,
+            error "Failed to install %F{blue}$failures%f"
+        )
+        exit 1
+    }
+PACMAN_INSTALL
+
+COPY --chmod=744 <<'FIX_USERADD' /app/fix-useradd-no-users
+#!/opt/bin/zsh
+    set -feo pipefail
+    stderr() {
+        print -Pr >&2 -- "$*"
+    }
+    if (( $(id -u) != 0 )) {
+        stderr 'You should run it as %F{magenta}root%f.'
+        exit 1
+    }
+
+    if ((! $+commands[groupadd])) {
+        cmd=(
+            /opt/bin/pacman-static
+            -Sy shadow
+            --overwrite '*'
+        )
+        print-cmd $cmd
+        $cmd || exit 127
+    }
+
+    cmd=(getent group users)
+    ! $cmd || {
+        stderr '%F{yellow}[WARN]%f do nothing!'
+        exit 0
+    }
+
+    cmd=(
+        groupadd
+        --gid 984
+        --system
+        --force
+        users
+    )
+    print-cmd $cmd
+    $cmd && {
+        stderr 'OK! Now try running %F{green}useradd %F{cyan}-m %F{blue}[username]%f (e.g., %F{green}useradd %F{cyan}-m%f user)'
+    }
+FIX_USERADD
 # ---------------------
 # ---------------------
 # FROM scratch
+# COPY --from=zsh / /
+# ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/local/games:/bin:/usr/games:/opt/sbin:/opt/bin
+# SHELL [ "/opt/bin/zsh", "--pipefail", "-fexc"]
 FROM zsh
-# ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/local/games:/bin:/usr/games:/opt/bin
-ARG BIN=/opt/bin/
-COPY --from=pacman-static --chmod=755 /app/zsh /app/pacman-static /app/pacman-conf-static ${BIN}
-
-COPY --chmod=755 <<'EOF' ${BIN}pacman
-#!/opt/bin/ash
-pacman=/opt/bin/pacman
-${pacman}-static -Syy pacman --overwrite '*' && {
-    [ -e /bin/pacman ] && {
-        rm -vf ${pacman}
-        echo >&2 "/bin/pacman $*"
-        /bin/pacman "$@"
-        echo >&2 "run 'hash -r' to reset the command hash table"
-    }
-}
-EOF
-
-# src: ../../ca-certificates/extracted/tls-ca-bundle.pem
-# link: /etc/ssl/certs/ca-certificates.crt
-ARG CA_FILE=/etc/ca-certificates/extracted/tls-ca-bundle.pem
-ARG TLS_CRT=/etc/ssl/certs/ca-certificates.crt
-COPY --from=arch ${CA_FILE} ${CA_FILE}
-COPY --from=arch ${TLS_CRT} ${TLS_CRT}
-COPY . /etc/
-
-RUN <<EOF
-    ln -svf ${CA_FILE} ${TLS_CRT}
-
-    cd /opt/bin
-
-    ln -svf $PWD/pacman-static /opt/pack
-
-    chmod 755 -v /etc/pacman.d
-
-    cd /etc/pacman.d/repos
-    for i (disabled/x86_64/*conf) {
-        cp -Lvf $i .
-    }
-
-    cd ../options
-    ln -svf bak/siglevel-never.conf ./sig-level.conf
-    mkdir -p /var/lib/pacman/
-EOF
-
+COPY --from=pacman-static --chmod=755 /app/* /opt/bin/
 CMD ["/opt/bin/ash"]
